import { ROLES, type RoleKey } from './roles';

export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_DISABLE: 'users.disable',

  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',

  TENANTS_READ: 'tenants.read',
  TENANTS_MANAGE: 'tenants.manage',

  BRANCHES_READ: 'branches.read',
  BRANCHES_MANAGE: 'branches.manage',

  WAREHOUSES_READ: 'warehouses.read',
  WAREHOUSES_MANAGE: 'warehouses.manage',

  INVENTORY_READ: 'inventory.read',
  INVENTORY_CREATE: 'inventory.create',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',

  PRODUCTS_READ: 'products.read',
  PRODUCTS_MANAGE: 'products.manage',

  RECEIVING_READ: 'receiving.read',
  RECEIVING_MANAGE: 'receiving.manage',

  PICKING_READ: 'picking.read',
  PICKING_MANAGE: 'picking.manage',

  SHIPMENTS_READ: 'shipments.read',
  SHIPMENTS_CREATE: 'shipments.create',
  SHIPMENTS_DISPATCH: 'shipments.dispatch',
  SHIPMENTS_DELIVER: 'shipments.deliver',

  REPORTS_READ: 'reports.read',
  REPORTS_EXPORT: 'reports.export',

  AUDIT_READ: 'audit.read',

  // Box catalog (Phase 2 — first slice). See openspec/changes/align-with-exspeed-workflows.
  BOX_CATALOG_READ: 'box-catalog.read',
  BOX_CATALOG_MANAGE: 'box-catalog.manage',

  // Service orders (Phase 2 — second slice).
  SERVICE_ORDERS_READ: 'service-orders.read',
  SERVICE_ORDERS_CREATE: 'service-orders.create',
  SERVICE_ORDERS_MANAGE: 'service-orders.manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export const ALL_PERMISSIONS: PermissionKey[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.WAREHOUSE_ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.BRANCHES_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.WAREHOUSES_MANAGE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.RECEIVING_READ,
    PERMISSIONS.RECEIVING_MANAGE,
    PERMISSIONS.PICKING_READ,
    PERMISSIONS.PICKING_MANAGE,
    PERMISSIONS.SHIPMENTS_READ,
    PERMISSIONS.SHIPMENTS_CREATE,
    PERMISSIONS.SHIPMENTS_DISPATCH,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.BOX_CATALOG_READ,
    PERMISSIONS.BOX_CATALOG_MANAGE,
    PERMISSIONS.SERVICE_ORDERS_READ,
    PERMISSIONS.SERVICE_ORDERS_CREATE,
    PERMISSIONS.SERVICE_ORDERS_MANAGE,
  ],
  [ROLES.WAREHOUSE_STAFF]: [
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.RECEIVING_READ,
    PERMISSIONS.RECEIVING_MANAGE,
    PERMISSIONS.PICKING_READ,
    PERMISSIONS.PICKING_MANAGE,
    PERMISSIONS.SHIPMENTS_READ,
    PERMISSIONS.BOX_CATALOG_READ,
    PERMISSIONS.SERVICE_ORDERS_READ,
    PERMISSIONS.SERVICE_ORDERS_CREATE,
    PERMISSIONS.SERVICE_ORDERS_MANAGE,
  ],
  [ROLES.DISPATCHER]: [
    PERMISSIONS.BRANCHES_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.SHIPMENTS_READ,
    PERMISSIONS.SHIPMENTS_CREATE,
    PERMISSIONS.SHIPMENTS_DISPATCH,
    PERMISSIONS.REPORTS_READ,
  ],
  [ROLES.DRIVER]: [PERMISSIONS.SHIPMENTS_READ, PERMISSIONS.SHIPMENTS_DELIVER],
  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.BOX_CATALOG_READ,
    PERMISSIONS.BOX_CATALOG_MANAGE,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.BRANCHES_READ,
    PERMISSIONS.WAREHOUSES_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.RECEIVING_READ,
    PERMISSIONS.PICKING_READ,
    PERMISSIONS.SHIPMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.BOX_CATALOG_READ,
    PERMISSIONS.SERVICE_ORDERS_READ,
  ],
};
